global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10s
  external_labels:
    environment: "production"
    project:     "gempawas-aftershock"

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"

  - job_name: "model-serving"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["nginx:80"]
        labels:
          service:   "model-serving"
          component: "inference"

  - job_name: "nginx"
    scrape_interval: 15s
    static_configs:
      - targets: ["nginx-exporter:9113"]
        labels:
          service:   "nginx"
          component: "load-balancer"
